# This workflow will build a golang project
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# https://docs.docker.com/build/ci/github-actions/

name: Test (Dev)

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - 'licenses/**'
      - '*.md'
      - '.gitignore'
      - '.gitattributes'
      - '.gitattributes'
      - 'LICENSE'
      - 'NOTICE'
      - '.github/**'

jobs:

  test_and_build_go:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: |
        go test -p 1 -coverpkg=./... -coverprofile=c.out -v ./...
        go tool cover -html=c.out -o coverage.html
      env:
        FLASHPIPE_DEBUG: true
        FLASHPIPE_TMN_HOST: equaliseit.it-cpi023.cfapps.eu20-001.hana.ondemand.com
        FLASHPIPE_OAUTH_HOST: equaliseit.authentication.eu20.hana.ondemand.com
        FLASHPIPE_OAUTH_PATH: /oauth/token
        FLASHPIPE_OAUTH_CLIENTID: ${{ secrets.OAUTH_CLIENTID }}
        FLASHPIPE_OAUTH_CLIENTSECRET: ${{ secrets.OAUTH_CLIENTSECRET }}
        FLASHPIPE_TMN_PASSWORD: ${{ secrets.BASIC_PASSWORD }}
        FLASHPIPE_TMN_USERID: ${{ secrets.BASIC_USERID }}
        FLASHPIPE_APIPORTAL_HOST: eu20apiportal.cfapps.eu20.hana.ondemand.com
        FLASHPIPE_APIPORTAL_OAUTH_CLIENTID: ${{ secrets.APIPORTAL_OAUTH_CLIENTID }}
        FLASHPIPE_APIPORTAL_OAUTH_CLIENTSECRET: ${{ secrets.APIPORTAL_OAUTH_CLIENTSECRET }}

    - name: Save output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: coverage.html
